from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities import Conversation, Guest, Message, User


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def create(self, email: str, password_hash: str) -> User: ...


class GuestRepository(Protocol):
    async def get_by_id(self, guest_id: UUID) -> Guest | None: ...
    async def create(self, guest_id: UUID | None = None) -> Guest: ...
    async def delete_older_than(self, cutoff: datetime) -> int: ...


class ConversationRepository(Protocol):
    async def get_for_user(self, user_id: UUID) -> Conversation | None: ...
    async def get_for_guest(self, guest_id: UUID) -> Conversation | None: ...
    async def create_for_user(self, user_id: UUID) -> Conversation: ...
    async def create_for_guest(self, guest_id: UUID) -> Conversation: ...


class MessageRepository(Protocol):
    async def list_before(
        self,
        conversation_id: UUID,
        *,
        limit: int,
        before_id: UUID | None,
    ) -> tuple[list[Message], bool]: ...
    async def add(self, conversation_id: UUID, role: str, content: str) -> Message: ...
    async def list_all_for_context(self, conversation_id: UUID) -> list[Message]: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class SessionStore(Protocol):
    def issue(self, user_id: UUID) -> str: ...
    def resolve(self, token: str) -> UUID | None: ...


class OllamaClient(Protocol):
    async def health(self) -> bool: ...
    def stream_chat(self, messages: list[dict[str, str]]) -> AsyncIterator[str]: ...


class UnitOfWork(Protocol):
    users: UserRepository
    guests: GuestRepository
    conversations: ConversationRepository
    messages: MessageRepository

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
