spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ai_qwen25_0_5b
    username: postgres
    password: postgres
app:
  ollama-base-url: http://127.0.0.1:11434
  ollama-model: qwen2.5:0.5b
  cookie-secure: false
