create table if not exists users (
  id uuid primary key,
  email varchar(320) unique not null,
  password_hash varchar(255) not null,
  created_at timestamp with time zone not null default now()
);

create table if not exists guests (
  id uuid primary key,
  created_at timestamp with time zone not null default now()
);

create table if not exists conversations (
  id uuid primary key,
  user_id uuid references users(id) on delete cascade,
  guest_id uuid references guests(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  constraint uq_conversations_user unique (user_id),
  constraint uq_conversations_guest unique (guest_id)
);

create table if not exists messages (
  seq integer generated by default as identity primary key,
  id uuid unique not null,
  conversation_id uuid not null references conversations(id) on delete cascade,
  role varchar(32) not null,
  content text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists ix_users_email on users(email);
create index if not exists ix_messages_id on messages(id);
create index if not exists ix_messages_conversation_id on messages(conversation_id);
create index if not exists ix_messages_created_at on messages(created_at);
